### ISSUE TITLE
Set up directory structure

### ISSUE THREAD

**Issue by yashpatel5400** [yashpatel5400/intertect#10]
Should use the node standard directory structure and explain it in the README

**Comment by pdelong** [comment]
There isn't really a standard node structure and since we're going to be statically generating and serving the website, my idea for the structure is to have a `templates/` directory that houses the pre-built site and a `public/` directory for the actual serving of the application once it's been built

~~This will be closed simultaneously with #11~~ (see below)

**Comment by pdelong** [comment]
Folder structure will be updated when we decide how we want the static generation to work. However, this will be a single extra folder so it won't be at all a large change
